[package]
name = "emqjs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
once_cell = "1.17.1"
rkyv = { version = "0.7.41", features = ["archive_le"] }
rquickjs = { version = "0.1.7", features = ["macro", "parallel"], optional = true }
walrus = "0.19.0"

[[bin]]
name = "emqjs_preprocess"
path = "src/preprocess.rs"

[lib]
name = "emqjs_runtime"
path = "src/runtime.rs"
crate-type = ["staticlib"]

[patch.crates-io]
rquickjs = { git = "https://github.com/RReverser/rquickjs", branch = "arraybuffer-view" }
